
project:
  type: website
  output-dir: _site

website:
  title: "Laboratorios RTOS"
  navbar:
    left:
      - href: demo.qmd
        text: Demo

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
